### PR TITLE
feat(widgets): :sparkles: Add Uptime Kuma Widget

### PR DESCRIPTION
**Pull request by imjimmeh**
[imjimmeh](https://github.com/imjimmeh) Medium [imjimmeh /feat/uptime-kuma-widget → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/feat/uptime-kuma-widget) Commits: 10 | Files Changed: 3 | Additions: 292 Label Unchecked Tasks [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 

Feature/new widget (and documentation to match)

**Overview**

- Adds a widget for basic Uptime Kuma statistics
- Currently supports:

1. Status (up/down)
2. Response time

There is more code to display whether the certificate is valid or not, and when the certificate expires, but I'm a terrible designer so I left those for now.

image

I've tried to use existing styling where possible, but again I am not a designer.

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
~~- [ ] _(If a new config option is added)_ Attribute is outlined in the schema and documented~~ N/A
~~- [ ] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance~~ N/A
- [ ] Bumps version, if new feature added **Do you count a new widget as a feature/version bump? I have not touched the version FWIW**

If there's any changes you'd request making please feel free.

### CODE REVIEW

**Review by Lissy93 — COMMENTED** [review]
Hey @imjimmeh 
All looks great, except I think your editor has auto-modified all of the widgets.md file, which is causing some conflicts.

I'm happy to update that so it only includes your addition, and the rest of the content remains untouched, if you need.

**Comment by imjimmeh** [comment]
Ah piss. Just noticed I somehow deleted some section? Might have reverted back a commit too far.

I'll fix it later tonight, unless you want to sort it out if you have time before I get to it 😄

**Comment by Lissy93** [comment]
> Ah piss. Just noticed I somehow deleted some section? Might have reverted back a commit too far.
> I'll fix it later tonight, unless you want to sort it out if you have time before I get to it 😄

No worries, I've added that back in :)

**Review by Lissy93 — APPROVED** [review]
Looks good!

**Pull request merged**
