### PR TITLE
:bug: On branch BUG/1608_glances-network-error

### PR DESCRIPTION
**Pull request by hockwill**
[hockwill](https://github.com/hockwill) Quick [hockwill /BUG/1608_glances-network-error → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/BUG/1608_glances-network-error) Commits: 2 | Files Changed: 2 | Additions: 0 Label [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
BUGFIX

**Overview**
Glances Widgets for Network Traffic and Interfaces were not correctly displaying information provided from the api response.

**Issue Number** #1608

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors
- [NA] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [NA] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [NA] _(If significant change)_ Bumps version in package.json

### CODE REVIEW

**Review by CrazyWolf13 — APPROVED** [review]
Awesome, just tested and all plugins except the IP plugin seems to work, (the IP plugin shows a message that the glances version is not compatible with that plugin)

Thanks for your contribution! ✨

**Comment by CrazyWolf13** [comment]
Fixes #1608 and #1594 🚀

**Comment by hockwill** [comment]
I can look again later this week at the ip plugin.
I suspect it is a similar problem in that the fields returned have changed
names.

**Comment by hockwill** [comment]
> Awesome, just tested and all plugins except the IP plugin seems to work, (the IP plugin shows a message that the glances version is not compatible with that plugin)

The glances  gl-ip-address widget seems to work with no errors? Where is the version error message?

**Review by Lissy93 — APPROVED** [review]
LGTM, thanks @hockwill and @CrazyWolf13

**Comment by hockwill** [comment]
I see this was approved a bit ago. Is there something else I need to do that I have not done?
Sorry for the close/open. I was seeing if it was something I needed to press.

**Comment by CrazyWolf13** [comment]
Yes, a merge was needed :).

**Pull request merged**
