### PR TITLE
Update authentication.md

### PR DESCRIPTION
**Pull request by dasunsrule32**
[dasunsrule32](https://github.com/dasunsrule32) Medium [dasunsrule32 /docs-oidc-authentik → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/docs-oidc-authentik) Commits: 1 | Files Changed: 1 | Additions: 180 Label Unchecked Tasks [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
> Documentation

**Overview**
> Add authentik specific documentation to get OIDC configured with Dashy.

**Issue Number** _(if applicable)_ #1664 

**New Vars** _(if applicable)_
> N/A

**Screenshot** _(if applicable)_
> N/A

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [x] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [x] _(If significant change)_ Bumps version in package.json

### CODE REVIEW

**Review by CrazyWolf13 — APPROVED** [review]
Awesome, thanks a lot! ✨🚀

**Comment by dasunsrule32** [comment]
You're welcome 🙂

**Review by Lissy93 — APPROVED** [review]
Looks great, thank you for adding!

**Comment by dasunsrule32** [comment]
You're welcome. I figured it would help others, so why not. 🙂

**Pull request merged**
