### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by alexdelprete**
[alexdelprete](https://github.com/alexdelprete) Medium [alexdelprete /master → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/master) Commits: 1 | Files Changed: 2 | Additions: 123 Quality Checklist Label

*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections that are not applicable)*

**Category**: 
Localization

**Overview**
Updated and Completed Italian Translation and corrected a minor mistake in the english translation (1 word).

### CODE REVIEW

**Review by Lissy93 — APPROVED** [review]
Looks great, thanks very much :)

**Comment by alexdelprete** [comment]
We need to thank you for the development of Dashy: you've made a fantastic job. Happy to help just a tiny bit. :)

BTW: in the en.json file, I translated the two last sections, but I had the feeling they were there by mistake (airlines?):

```json
    "flight-data": {
      "arrivals": "Arrivals",
      "departures": "Departures"
    },
    "tfl-status": {
      "good-service-all": "Good Service on all Lines",
      "good-service-rest": "Good Service on all other Lines"
    }
```

**Comment by Lissy93** [comment]
Thank you for your kind words, very glad you're enjoying it :)

Those last two translations are used by [widgets](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md),-  I think the Flight data and Train status widgets

**Comment by alexdelprete** [comment]
> Those last two translations are used by [widgets](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md),- I think the Flight data and Train status widgets

Incredible, I didn't even know there were widgets (still reading TFM) !! 🤣 

Amazing work Lissy. 👏🏼

**Comment by alexdelprete** [comment]
Forgot to edit the README.md to update the language section and delete the "machine translated" string for Italian. Can you take care of that? Thanks.

**Pull request merged**
