### PR TITLE
✨ Tactical RMM Widget

### PR DESCRIPTION
**Pull request by conlan0**
[conlan0](https://github.com/conlan0) Medium [conlan0 /master → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/master) Commits: 4 | Files Changed: 4 | Additions: 264 Label Unchecked Tasks [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: Feature

**Overview**
Added Tactical RMM server status widget
This widget uses the built-in monitoring endpoint of a hosted Tactical RMM instance and displays the data returned
 to monitor your server's status the widget uses 2 options (url and token) to connect to your server and start displaying the status data.

Also made a slight change to the cors-proxy to send the request body as `data` instead of `json`. (I have tested with some widgets to assure no functionality loss but not all widgets)

**Screenshot**
> 
image

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [x] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance

### CODE REVIEW

**Review by Lissy93 — APPROVED** [review]
This looks really nice! :)

**Review by Lissy93 — APPROVED** [review]
This looks awesome!

**Comment by CrazyWolf13** [comment]
@Lissy93  Can the useProxy data just be changed to json without breaking anything?

**Comment by Lissy93** [comment]
Oops, I think you're right. I'm just testing now..

**Comment by conlan0** [comment]
Thank you i'm glad you like it! i did test data with a few of the other widgets but i dont have all the services needed so i couldnt do all of them but i believe it should work for all because `data` is the standard in Axios for sending the request body, and using it ensures compatibility with most RESTful APIs

**Pull request merged**
