### PR TITLE
[FIX] Rename pre-build to pre_build

### PR DESCRIPTION
**Pull request by evroon**
Quick evroon /feature-arm-docker → Lissy93/dashy Commits: 1 | Files Changed: 1 | Additions: 0 evroon [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
Bugfix for ARM build hook for DH builds.

**Overview**
Fix for PR #130

**Issue Number** #117

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] Bumps version, if new feature added

### CODE REVIEW

**Review by Lissy93 — APPROVED** [review]

**Comment by evroon** [comment]
Ah is it still failing with the same error?

**Comment by Lissy93** [comment]
Yup, it is :/ I'm going to make a GH action, which should hopefully work. 🤞 
I'll let you know when it's done, and thanks so much for all your help :)

**Comment by Lissy93** [comment]
Oh wait- the arm32v7 build is working!!!!!!!
 That's awesome! Thanks so much for that 😇
 I will look into the arm64v8 build

**Comment by evroon** [comment]
Cool!
The docker image is indeed working nicely on my rpi4.

There seems something wrong with the `arm64v8/alpine` image, I can't build `Dockerfile-arm64v8`, it gives:
```standard_init_linux.go:211: exec user process caused "no such file or directory"``` at the first RUN line, whatever command you give it.

**Pull request merged**
