### PR TITLE
Add config option to disable all UI config features for non admin users.

### PR DESCRIPTION
**Pull request by Cereal916**
[Cereal916](https://github.com/Cereal916) Medium [Cereal916 /disableConfigurationForNonAdmin → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/disableConfigurationForNonAdmin) Commits: 3 | Files Changed: 4 | Additions: 8 Label

**Category**: 
>  Feature 

**Overview**
> Provides an option to allow admin functionality while still hiding local auth configurations from non admin users.

**New Vars** _(if applicable)_
> Config file option: disableConfigurationForNonAdmin

**Code Quality Checklist** _(Please complete)_
- [ X ] All changes are backwards compatible
- [ X ] All lint checks and tests are passing
- [ X ] There are no (new) build warnings or errors
- [ X ] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [ X ] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [ X ] Bumps version, if new feature added

### CODE REVIEW

**Review by Lissy93 — APPROVED** [review]
Sorry for the delay, I was initially unsure weather having too many config options for managing permissions would become confusing for the user, or hard to maintain in the code base, but thinking about it- I do see the value for this option.

Approved.

**Comment by Cereal916** [comment]
Thanks @Lissy93. My motivation for this is just security by obscurity. I don't want other logged in users to see other userId's, hashed pw's or services that are hidden to them. Prob overkill since anyone with a user account is very likely not a bad actor, but it makes me feel better :).

**Comment by Lissy93** [comment]
In #799 I'm adding some proper backend security measures, which should make things a lot better :)

The multi-user functionality, was all added incrementally as each feature was requested, and so not planned from a high level, like it should have been. Currently, any logged in user can use the developer tools, to find certain info from other users, which is far from ideal - just something to be aware of. I am fixing that in the next update.

**Comment by Cereal916** [comment]
Sweet, sounds like it'll prob take care of most of what was in my PR's XD. Hopefully I didn't just gunk up your merge.

Looking forward to the update.

**Pull request merged**
