### PR TITLE
Fix arm64v8 Dockerfile

### PR DESCRIPTION
**Pull request by evroon**
Quick evroon /fix-docker-arm64v8 → Lissy93/dashy Commits: 1 | Files Changed: 1 | Additions: 0 evroon [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
Bugfix

**Overview**
Fixes `Dockerfile-arm64v8`. 

**Issue Number**  #117

**Code Quality Checklist**
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] Bumps version, if new feature added

### CODE REVIEW

**Review by Lissy93 — APPROVED** [review]

**Comment by Lissy93** [comment]
Thanks so much, fingers crossed this will work :)

**Comment by Lissy93** [comment]
If it doesn't work, I think I've just managed to get a version running using `node:lts-alpine` as the base and [multiarch/qemu-user-static](https://github.com/multiarch/qemu-user-static/) for the ARM 64 part. Looks like it's working on DockerHub, and the build time wasn't too long, but haven't yet tested it on my Pi

**Comment by evroon** [comment]
Ah the image is now on DockerHub.

**Comment by Lissy93** [comment]
Awesome, your fix is working! 
This is amazing, I'm a proper noob at Docker, and spent ages yesterday trying to figure this out, so I'm super happy it's working now, you're really good at this, thanks so much for the PR's :) Your container is now live on Docker Hub, and all green
image

**Comment by evroon** [comment]
Haha no problem, I'm glad it's working. I wish I knew as much as you do about Vue.js etc. ;)

**Pull request merged**
