### PR TITLE
📝Fix grammer - Make easier to read🔀

### PR DESCRIPTION
**Pull request by walkxcode**
[walkxcode](https://github.com/walkxcode) Medium [walkxcode /Grammer → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/Grammer) Commits: 1 | Files Changed: 1 | Additions: 0 Label

Your documentation may be grammatically correct, but sometimes it's wordy and hard to read. Walkx can help you! Try Walkxarly now at https://walkx.org! 😅 _(Grammarly reference)_

**Category**: 
> Documentation

**Overview**
> Fixed punctuation.
> Made some words like `Favicon` or `config` more consistent throughout the documentation.
> Rewrote some sentences.
> I don't even remember what I did... I just wrote.

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backward compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [x] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [x] Bumps version, if new feature added

### CODE REVIEW

**Comment by walkxcode** [comment]
Considering if I should do the whole /docs folder too... I'm quite bored... 👀

**Comment by walkxcode** [comment]
😭

**Comment by walkxcode** [comment]
now its funny because grammar is written incorrectly everywhere

**Comment by Lissy93** [comment]
That's a lot of changes, lemme have a read through. Thanks so much :)
> now its funny because grammar is written incorrectly everywhere

Yeah, I guess writing human English isn't my strong point :(

**Review by Lissy93 — APPROVED** [review]
LGTM :)

**Comment by walkxcode** [comment]
👍

**Pull request merged**
