### PR TITLE
[DRAFT] Update French translation 

### PR DESCRIPTION
**Pull request by EVOTk**
[EVOTk](https://github.com/EVOTk) 🌐 Language Update Quick [EVOTk /patch-fr-1.9.1 → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/patch-fr-1.9.1) Commits: 2 | Files Changed: 1 | Additions: 3

*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections that are not applicable)*

Hello :) ,
Update FR translation

**Can you give me the context for using:**
"edit-raw-config-btn": "Edit Raw Config",
"edit-raw-config-tooltip": "View and modify raw config via JSON editor",

Thank you

**Category**: Improvement

Overview
Update French translation 

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors

### CODE REVIEW

**Comment by Lissy93** [comment]
Thanks @EVOTk :)

Sure, the `edit-raw-config-btn` button is visible when in edit mode, and it just opens up the old JSON editor, and the tooltip shows a description on hover.

image

Maybe I should come up with a better name for the raw config editor 🤔...

**Comment by EVOTk** [comment]
What do you think of YAML Mode? 
I also think this button shouldn't be in the options in the "Config Saveing Options", when do you think?

>"edit-raw-config-btn": "YAML Mode",
>"edit-raw-config-tooltip": "View and modify YML config via JSON Editor",

In French : 
>"edit-raw-config-btn": "Mode YAML",
>"edit-raw-config-tooltip": "Consulter et modifier la configuration YML à l'aide de l'éditeur JSON",

**Comment by Lissy93** [comment]
I think you are right. It makes things look too complicated with so many buttons there.
I originally put it there, as there are a few settings which can't yet be managed with the new editor, but can with the JSON editor. But actually, users can still use JSON editor in edit mode, they just have to open the main Config menu

**Review by Lissy93 — APPROVED** [review]

**Comment by EVOTk** [comment]
What do you want to do with this PR?
So there is no more need to translate dit-raw-config-btn "and" edit-raw-config-tooltip "for the moment?

**Review by Lissy93 — APPROVED** [review]

**Comment by Lissy93** [comment]
So I removed the text for the cloud button and JSON editor button. The rest of your changes are still needed, so this PR is ready to be merged now :)

**Pull request merged**
