### PR TITLE
[FEATURE] Option for Ping-Only Status Checks

### PR DESCRIPTION
**Pull request by Lissy93**
Medium [Lissy93 /FEATURE/ping-only-status-check-option → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/FEATURE/ping-only-status-check-option) Commits: 14 | Files Changed: 18 | Additions: 125 ✨ Feature 🚫 Merge Conflicts

**Category**: Feature

**Overview**
Several users have faced issues either with certain services having failing status checks, or being unable to check the status of web services that don't render any content (such as game servers, mail servers, file servers, etc). This is because the default status check option works by sending an empty GET request to the URL, which obviously cannot work for services that are not designed to accept these requests.

This PR introduces a new option,  `statusCheckPingOnly`. If this is set to true for a given service, then just a traditional ping will be sent to that IP address. 

**Issue Number**: #181 (Kinda sort of related)

**New Vars** 
**`statusCheckPingOnly`** (`boolean`  _Optional_) If enabled, instead of sending a HTTP request, this option will use a simple ping to your app

**Screenshot** N/A

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors
- [X] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [X] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [X] Bumps version, if new feature added

### CODE REVIEW

**Comment by Lissy93** [comment]
Hmm, so it turns out that net-ping [requires Python](https://github.com/nospaceships/node-net-ping/issues/24) to work, and I do not want to add this to the Docker container, since it adds additional weight.

I need to either find a cross-platform method of pinging an endpoint, or figure out how to sort the net-ping node-gyp issue. I really should have looked into that before building this feature out 🤦

**Comment by Lissy93** [comment]
Actually including: `apk add --update python make g++ && rm -rf /var/cache/apk/*` fixed it.
However I am worried that less experienced users, running without Docker may get confused by this. Plus I want to try and keep the container as small as possible.

The Docker image would be a lot more light-weight if I re-wrote the server-side stuff in Go instead of Node. And in doing so, the ping functionality would be easy. But since that'd be a big task, it will have to wait till I have some spare time.

**Comment by masterwishx** [comment]
Sorry for missunderstanding ,so what should we do ?

run in consol ?
apk add --update python make g++ && rm -rf /var/cache/apk/*e

**Comment by Lissy93** [comment]
No, because this feature was never merged (it's closed). So it's not possible to use it. I mentioned this in your other thread.

**Comment by masterwishx** [comment]
you said i can somehow to ping no ?

**Comment by Lissy93** [comment]
I said it's been discussed before, and isn't possible in dashy. You'll need to write a script yourself. But I'm 90% sure you can get status checking working by following the docs.

Feel like this is goning round in circles now.

**Comment by masterwishx** [comment]
OK Thanks a lot i will try ..

**Pull request closed without merging**
