### PR TITLE
Large Widgets 

### PR DESCRIPTION
**Pull request by Nexow91**
[Nexow91](https://github.com/Nexow91) Extra Large [Nexow91 /WEBSITE/docs-site-source → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/WEBSITE/docs-site-source) Commits: 70 | Files Changed: 408 | Additions: -3593 Category Overview Quality Checklist Label

Hello, first of all, thank you for Dashy, I find it particularly good to use it.

Unfortunately I have a problem with the widget. Here it is not one and the same widget with multiple items displayed next to each other. For example, I have over 13 ads on Statping. When there are 12 ads, the last ad is cut off or not visible. Unfortunately, even if I set Rows and Columns to 1 digit (small), the widget is not displayed.

I thought I could use the "itemSize" command to change the amount of ads in the widget, but that wasn't possible.

Unfortunately, "cutToHeight" did not produce any results either.

Maybe I just have to use the Statping API to display the groups and I'm currently stumped by their content.

My question.
Is there a way to display long widgets side by side?

In this case, several widgets that refer to a URL also make no sense because otherwise twice the number of the same ads would be visible.

I look forward to your feedback and thank you again for Dashy and the support :)

screencapture-192-168-2-80-4000-2022-05-24-20_05_18

### CODE REVIEW

**Review by Lissy93 — COMMENTED** [review]
I am very confused about this PR, why are you reverting tons of changes? I can't tell what you're trying to do...

But from your description, it sounds like the solution to your issue is just to set the `--section-max-height` to a larger number. 
For example, using the custom CSS option, add: `html { --section-max-height: 6000px; }`.

**Comment by Nexow91** [comment]
> I am very confused about this PR, why are you reverting tons of changes? I can't tell what you're trying to do...
> 
> But from your description, it sounds like the solution to your issue is just to set the `--section-max-height` to a larger number. For example, using the custom CSS option, add: `html { --section-max-height: 6000px; }`.

-----------------------------------------------------------------------------------------------------------------------------------

Hello, thank you for the feedback and for the tip with CSS.

The problem was the widget was too long, so I wanted to split the widget horizontally, which is only lengthening.

I have included an image below for this.

I thought it would be possible to include the commands in the Github documentation in the widget tab, but I was wrong.


screencapture-192-168-2-80-4000-2022-05-24-20_05_18

**Comment by Lissy93** [comment]
Ah okay, I think this could be done with a [grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout), alternatively by splitting them into separate sections.

**Comment by Lissy93** [comment]
I'm going to close this PR, since there are merge conflicts, and I can't see what changes you were trying to make.

But if you can rebase your branch from master, and submit a new PR with **just your changes**, I'd be happy to review it, give feedback, and merge it if it's working and neat :)

**Comment by Kiuber** [comment]
> I am very confused about this PR, why are you reverting tons of changes? I can't tell what you're trying to do...
> 
> But from your description, it sounds like the solution to your issue is just to set the `--section-max-height` to a larger number. For example, using the custom CSS option, add: `html { --section-max-height: 6000px; }`.

maybe `:root { --section-max-height: 6000px; }`

**Pull request closed without merging**
