### PR TITLE
[FEAT] Remove the need for rebuild after config changes

### PR DESCRIPTION
**Pull request by Lissy93**
🏗️ Architecture Extra Large [Lissy93 /FEAT/Dashy-V3 → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/FEAT/Dashy-V3) Commits: 76 | Files Changed: 97 | Additions: 1474 [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

This is a big one...

> [!NOTE]
> See #1529 for upgrade details

- Read config at runtime, not build-time (no more rebuilds!)
- Use a directory instead of file for user-provided assets
- Handle and serve up user-data in the web server
- Accept env vars for widget secrets (Re: #1438)
- Switch Docker port, from 80 to 8080 (non-root container)
- Fix local config saving, multi-page support and some other things
- Updated docs to reflect all the above changes
- Added a new theme (glass)

**Category**:  Feature

**Overview**
- Fetch the config file client-side, instead of compiling the app with the config file. This means you can change the config, without needing to recompile the app!
- Changed the location of user data, from a single file to a directory (`/public/conf.yml` to `/user-data/...`)
- Some other stuff (I'll add here soon...)

**Issue Number** 
// TODO: Find and tag related issues

**New Vars**
N/A

**Screenshot** 

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [x] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [x] Bumps version, if new feature added

### CODE REVIEW

**Comment by Lissy93** [comment]
### TODO
- [ ] Update Dockerfile to use new paths
- [ ] Fix insufficient null checks (raised by Deepscan, [here](https://deepscan.io/dashboard/#view=project&tid=12411&pid=18128&bid=437203&subview=pull-request&prid=1886462))
- [ ] Update docs: Deployment  and Configuring
- [ ] Test on different platforms
- [ ] Complete the PR body (above), and prepare discussion announcement outlining changes
- [ ] .....

**Comment by CrazyWolf13** [comment]
Looks awesome,, very excited!

Just quickly cloned and used the new FEAT v3 branch, got some errors on yarn buil-and-start:

Not sure if the commands were the same, but got it mostly working with `yarn` and `yarn build-and-start`, correct?

````
Using Dashy V-3.0.0. Update Check Complete
✅ Dashy is Up-to-Date


 WARN  A new version of sass-loader is available. Please upgrade for best experience.
⠴  Building for production...

 WARNING  Compiled with 3 warnings                                         9:49:57 PM

 warning  in ./src/utils/HeaderAuth.js

Module Warning (from ./node_modules/thread-loader/dist/cjs.js):

/root/dashy/src/utils/HeaderAuth.js
  41:17  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)


 @ ./src/main.js 28:0-73 81:13-32 82:4-18
 @ multi ./src/main.js

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  fonts/Raleway-Variable.3b5635ac.ttf (302 KiB)
  js/chunk-204c2a20.f6fab082.js (248 KiB)
  js/chunk-vendors.a867cf96.js (6.2 MiB)
  js/dashy.4a811c5c.js (763 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  dashy (7.18 MiB)
      css/chunk-vendors.d8067ad8.css
      js/chunk-vendors.a867cf96.js
      css/dashy.242caa32.css
      js/dashy.4a811c5c.js
`````

More TODO:

- Remove rebuild texts
> image
> Apologies for the german text :/

While testing I noticed a page reload is insanely fast now, really like that!

Edit via GUI-Editor works fine, however direct editing through "edit application settings" and "change config" seem to save but never apply

**Comment by Lissy93** [comment]
> Not sure if the commands were the same, but got it mostly working with yarn and yarn build-and-start, correct?

Yup, those commands are still correct

Though before merge, I might change to `yarn` (install) `yarn build` (build) and `yarn start` (start), because that's the more conventional way

---

> Just quickly cloned and used the new FEAT v3 branch, got some errors on yarn buil-and-start:

My bad, looks like I left a console.log statement in 🙈

---

> Would V3 also technically allow the main page to be a raw text files served from for example github raw?

Yes! 

Super easy to implement, so I just pushed a change in 49eb262465737c61aec28e159ceaa10a0486e8f6 which let's you change the location of the config file to use something other than `/conf.yml`, including a remote link like a GitHub Gist.

Obvs saving edits won't work. And there might be come caveats, like if where you're hosting your config has a CORS rule. But it works great with a GitHub Gist.

E.g. running `VUE_APP_CONFIG_PATH='https://snippet.host/zcom/raw' yarn build-and-start` will start the app with that remote public config

---

> Noticed you made an update to de footer, why did you put a "using: " there? is that still a placeholder?

Oops, yes - I was testing that it would read the right config when multiple config files are passed in. I'll remove

**Comment by CrazyWolf13** [comment]
> Super easy to implement, so I just pushed a change in [49eb262](https://github.com/Lissy93/dashy/commit/49eb262465737c61aec28e159ceaa10a0486e8f6) which let's you change the location of the config file to use something other than `/conf.yml`, including a remote link like a GitHub Gist.
> 
> Obvs saving edits won't work. And there might be come caveats, like if where you're hosting your config has a CORS rule. But it works great with a GitHub Gist.
> 
> E.g. running `VUE_APP_CONFIG_PATH='https://snippet.host/zcom/raw' yarn build-and-start` will start the app with that remote public config
> 

Awesome, Thank you!

I'll just do some testing on the new branch, lmk if I test anything specifically 👍

**Comment by Lissy93** [comment]
I've published a temprary tag to DockerHub (`v3-pre-release`) to make testing a bit easier

```bash
docker run -p 8080:8080 lissy93/dashy:v3-pre-release
```

or

```bash
docker run \
-p 8081:8080 \ 
-v /workspaces/dashy/my-dashy-assets:/app/user-data \
lissy93/dashy:v3-pre-release
```

Since that tag was built manually, it's not cross-platform, will only work with `linux/amd64`.
Course the real version, once merged will work everywhere.

**Comment by Lissy93** [comment]
All ready now!
I'll come back to this tomorrow evening, double check everything, and merge.

**Comment by CrazyWolf13** [comment]
> All ready now! I'll come back to this tomorrow evening, double check everything, and merge.
@Lissy93 
👍

In quick-start.md the port should also be changed to 8080:8080 instead of 8080:80 ?

**Comment by Lissy93** [comment]
Oh yeah, you're right, I forgot to update port number in the docs. That should be done now :)

**Review by CrazyWolf13 — APPROVED** [review]

**Pull request merged**
