### PR TITLE
Move config.yml to config subdirectory

### PR DESCRIPTION
**Pull request by bajo**
[bajo](https://github.com/bajo) Medium [bajo /master → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/master) Commits: 1 | Files Changed: 8 | Additions: 0 🚫 Merge Conflicts [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

Allows to use a folder as docker volume (eg. NFS share).
Addresses https://github.com/Lissy93/dashy/issues/1322

*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections that are not applicable)*

**Category**: 
> Feature

**Overview**
> Moves the conf.yml into a new subdirectory `config`, so that this whole folder can be bind mounted into the docker container. That way we can have a docker volume from NFS (or similar).  

**Issue Number** _(if applicable)_ #1322 

**New Vars** _(if applicable)_
> If you've added any new build scripts, environmental variables, config file options, dependency or devDependency, please outline here

**Screenshot** _(if applicable)_
> If you've introduced any significant UI changes, please include a screenshot

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [x] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [x] Bumps version, if new feature added

### CODE REVIEW

**Comment by bajo** [comment]
Might also address a subset of #693

**Review by joshbuker — APPROVED** [review]
Simply moves the conf.yml file into a `config/` folder, and updates any references to conf.yml to use the new location.

LGTM.

Dockerfile changes appear to also include changing the line endings.

**Comment by Lissy93** [comment]
Cheers @bajo and @joshbuker  - sorry this took so long to come around to. Given it was a breaking change it made sense to include it with the other breaking changes (for no app rebuilding) and do a major version bump, which took me longer than expected to get finished.

**Comment by joshbuker** [comment]
> Cheers @bajo and @joshbuker  - sorry this took so long to come around to. Given it was a breaking change it made sense to include it with the other breaking changes (for no app rebuilding) and do a major version bump, which took me longer than expected to get finished.

All good! Really appreciate your work!

**Comment by bajo** [comment]
> Cheers @bajo and @joshbuker - sorry this took so long to come around to. Given it was a breaking change it made sense to include it with the other breaking changes (for no app rebuilding) and do a major version bump, which took me longer than expected to get finished.

Thanks a lot @Lissy93 . Glad it made it into the release. :)

**Pull request closed without merging**
