### PR TITLE
[FEAT] Clearer error messaging and documented user-data dir (3.0.1)

### PR DESCRIPTION
**Pull request by Lissy93**
✨ Feature 📕 Docs Large [Lissy93 /FEAT/3.0.1-improvements → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/FEAT/3.0.1-improvements) Commits: 37 | Files Changed: 41 | Additions: 490 [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
Better troubleshooting. More secure auth. Refactors. Bug fixes

**Overview**
- Show more detailed message when Dashy fails to load (see screenshot below)
- Put all config.backup.***.yml in own folder inside user-data, so it doesn't clutter up the root
- Add support for HTTP auth, to protect config from unauthorized access
- Add support for environmental variables for auth passwords (instead of hashes)
- Fix the Item Size and Layout buttons, and add support for different settings for sub-pages
- Disable configuration edit options for guests, when auth enabled
  - #1552
- Update docs to include directory structure of `./user-data`
  - #1538
- Made cards hyperlinks to repos in GitHub widget
  - #1531
- Apply page title, from `pageInfo.title`
  - #1544
- Update Docker start command, to remove the build on first container start
  - #1543
- Fix Collapsed state persisting over different pages 
  - #1546
- Remove the automation where @liss-bot prompts non-stargazers to star the repo on ticket open
  - #1412
- Update widget fetch function to send user-specified headers
  - #1549
- Updated README.md to include sponsored message from Umbrel  

**Issue Number** _see above_

**New Vars** N/A

**Screenshot** _(if applicable)_

| Before | After |
|---|---|
| image | image |

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors
- [X] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [X] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [X] Bumps version, if new feature added

### CODE REVIEW

**Review by Lissy93 — COMMENTED** [review]
I think ready for merge

**Review by CrazyWolf13 — APPROVED** [review]
🚀 Looks awesome,
✨ And good to me !
🎉

**Comment by CrazyWolf13** [comment]
@Lissy93 While you are at it, could you increase the time limit before possible error screen pops up on initial build ?

Noticed, that on lower end devices that screen will pop up, but after waiting like 30-60sec more it works just fine after reloading the page.

**Comment by Lissy93** [comment]
> While you are at it, could you increase the time limit before possible error screen pops up on initial build ?

Yes! Will do now :)

But since the Dockerfile now doesn't build the app in the run stage, this screen should be seen much less often.

**Pull request merged**
