### PR TITLE
:sparkles: Feature: add user defined environment variables

### PR DESCRIPTION
**Pull request by zigotica**
[zigotica](https://github.com/zigotica) Medium [zigotica /FEATURE/environment-variables → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/FEATURE/environment-variables) Commits: 3 | Files Changed: 4 | Additions: 23 🚫 Merge Conflicts [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
Feature

**Overview**
Add user defined environment vars parser to avoid leaking secrets

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [x] Bumps version, if new feature added

### CODE REVIEW

**Comment by zigotica** [comment]
Hi @Lissy93  Thank you so much for this great dashboard! 
I added documentation and example for pihole widget, we can extend this to any other widget very easily. Hope you like it.

**Comment by zigotica** [comment]
Hi again @Lissy93 Sorry I haven't seen your reaction to first message, had a traffic accident and still under recovery. Apparently you seemed fond of the feature.

When I can be back, would you still be interested in me fixing the conflicts? Please be aware, they seem to be caused by a strange spacing in your text files. I can either remove my documentation changes and keep your files, or "fix" them (but they will actually bring more spacing issues if the MR takes long to be merged). 

Also, would you be interested in me applying the same approach in other widgets?

**Review by Lissy93 — COMMENTED** [review]
Hey @zigotica - sorry to hear about your traffic accident, are you recovering okay??

Your PR looks awesome, and is definitely the correct approach.

Let me finish off #1528, then I'll rebase your PR and get it merged :)

And sorry for the delay in responding, this totally slipped my mind.

**Comment by Lissy93** [comment]
Actually, would you be able to switch the target branch for your PR into `FEAT/Dashy-V3`? That way I can get it released sooner.
Alternatively, I can just copy your changes over to that branch

**Comment by zigotica** [comment]
Hi again @Lissy93 
I´m recovering slower than I expected, but all good, thank you. 
I just changed the target branch as you suggested

**Comment by zigotica** [comment]
Also, I am happy if you change what you need, not sure I'll be able to follow up this thread soon-ish. A pity cause I think it was going to be quite easy to update the rest of the widgets, I am happy if you continue the job (if you want) or I can do it when I am fully recovered (it can be some weeks)

**Review by Lissy93 — APPROVED** [review]

**Comment by Lissy93** [comment]
Well I'm wishing you all the best with your recovery 🌼🤗🧡

I've merged into the 3.0 branch, and will let you know once available in master- shouldn't be too long!

**Review by sunandthemoon — COMMENTED** [review]
8080

**Review by sunandthemoon — COMMENTED** [review]
Glass

**Pull request merged**
