### PR TITLE
[FEATURE] WIP: Introduces Multi-Page Support

### PR DESCRIPTION
**Pull request by Lissy93**
**Category**:   Feature

**Overview**
Implements support for multi-page dashboard, enabling users to have multiple dashboards using a single instance of Dashy.

**Issue Number** N/A

**New Vars**
- `appConfig.additionalConfigFiles` - An array of file names, referencing other config files.

**Screenshot** N/A

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors
- [X] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [X] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance

### CODE REVIEW

**Comment by Lissy93** [comment]
### Multi-Page: Usage 
This feature is still in it's infancy, and implementation is subject to change, some of which may not be backwards compatible.

At present, to use multiple pages, you need to create a new config file for each additional page. Store these files in `/public/configs/[route-name].conf.yml`. Then, in your main `conf.yml` file, under `appConfig` add an array of page names.

For example, if I had two new config files located in `/public/configs/home-lab.conf.yml` and `/public/configs/bookmarks.conf.yml`, then my main conf.yml would include the following:

```yaml
appConfig:
  additionalConfigFiles: [home-lab.conf.yml, bookmarks.conf.yml]
```

You will then see links to these pages appear in the navigation bar, and clicking each link will take you to that page.

**Comment by Lissy93** [comment]
Although this does technically work, the implementation is not very neat, and will likely cause issues later down the line. For this reason I'm closing this PR for now, but I will be adding Multi-Page support in the future, and it will be much better implemented than this.

In the meantime, the only way to have multiple pages is to spin up multiple Docker containers, and then link them together using the [`pageInfo.navLinks`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#pageinfonavlinks-optional).

**Comment by jvteleco** [comment]
Hi Lissy93, not sure if this Feature is still on your radar. I think it would be a great addition. 

Spinning multiple Dockers of course is an option, but eventually is not the same running a single one than three of them in terms of RAM in a raspberry or a small server (especially when you rebuild, RAM goes from 200MB up to 1GB).

Thanks.

**Comment by Lissy93** [comment]
Heya @jvteleco 
Don't worry, it deffo is still planned. It's on the [Current Roadmap 🛣️](https://github.com/Lissy93/dashy/discussions/405), so hopefully will up next soon.
Architecturing this feature was trickier than I anticipated, so any help would be great if your up for it, no worries if not.

**Pull request closed without merging**
