### PR TITLE
[FEATURE] Extend visibility to section items

### PR DESCRIPTION
**Pull request by pinarruiz**
[pinarruiz](https://github.com/pinarruiz) ✨ Feature Medium [pinarruiz /feature/extend-visibility-items → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/feature/extend-visibility-items) Commits: 14 | Files Changed: 8 | Additions: 150

**Category**: 
> Feature / Documentation

**Overview**
> Add support / extending keycloak and users visibility to section items.

**Issue Number** #664

**New Vars**
> config file options: Add displayData to items on sections

**Code Quality Checklist** _(Please complete)_
- [X] All changes are backwards compatible
- [X] All lint checks and tests are passing
- [X] There are no (new) build warnings or errors
- [X] Attribute is outlined in the schema 
- [X] Attribute is documented (Please read https://github.com/Lissy93/dashy/pull/691#issuecomment-1144057270)
- [x] Bumps version, if new feature added

### CODE REVIEW

**Comment by pinarruiz** [comment]
Since i am very new not only to JavaScript but Vue i have not done any documentation in case the code is unusable. Also, i do not know if sections that have all of its items invisible should be visible.

Waiting on some feedback to start or not documenting.

**Comment by Lissy93** [comment]
First impressions are that this looks like really awesome work :) 
I'll read through it properly in the morning, and get it reviewed.
Thank for submitting!

**Comment by pinarruiz** [comment]
> First impressions are that this looks like really awesome work :) I'll read through it properly in the morning, and get it reviewed. Thank for submitting!

Thanks for the feedback!

if when you get to review it you think it is mergeable i will work on the documentation for it.

**Review by Lissy93 — APPROVED** [review]
Tested and it works perfectly, code is great too.
Considering your new to JS + Vue, this is really awesome work :)

Approved, you ready for it to be merged?

**Comment by pinarruiz** [comment]
> Tested and it works perfectly, code is great too. Considering your new to JS + Vue, this is really awesome work :)
> 
> Approved, you ready for it to be merged?

Everything good on my end, so if you want to merge it is ok for me, when do you think it will be released? I did not bump the version on the package json as i do not know if i should.

**Pull request merged**
