### PR TITLE
[Docs] Config not saving troubleshooting

### PR DESCRIPTION
**Pull request by CrazyWolf13**
[CrazyWolf13](https://github.com/CrazyWolf13) Medium [CrazyWolf13 /master → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/master) Commits: 4 | Files Changed: 2 | Additions: 22 Label Unchecked Tasks [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)

**Category**: 
> Docs

**Overview**
> Added the config not saving troubleshooting mentioned in #1147

**Issue Number** _(if applicable)_ #1147 

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [ ] Bumps version, if new feature added

### CODE REVIEW

**Review by Lissy93 — COMMENTED** [review]
I do already have a WIP update on this in c8b3047356406472ac3151feea8dbb8b37246d1e
Tho actually your explanation does look clearer

**Comment by CrazyWolf13** [comment]
> I do already have a WIP update on this in [c8b3047](https://github.com/Lissy93/dashy/commit/c8b3047356406472ac3151feea8dbb8b37246d1e) Tho actually your explanation does look clearer

Ohhps, did not see that, looked into the other 2.1.2 branch.

If you like mine more, I can integrate your texts as well, so we can have only one PR about this. Otherwise I'll close mine.

**Comment by CrazyWolf13** [comment]
@Lissy93 Included you texts right into mine. Apologizes for interfering with your PR.

**Review by Lissy93 — APPROVED** [review]
no worries, looks good, will merge now

**Pull request merged**
