### PR TITLE
🛠️ Fix: Remove dashes in arch tags

### PR DESCRIPTION
**Pull request by walkxcode**
[walkxcode](https://github.com/walkxcode) Quick [walkxcode /patch-1 → Lissy93/dashy](https://github.com/Lissy93/dashy/tree/patch-1) Commits: 2 | Files Changed: 1 | Additions: 0 Quality Checklist Label

*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections that are not applicable)*

**Category**: 
> Documentation Fix

**Overview**
> Removed the dashes in the architecture tags.

### CODE REVIEW

**Comment by Lissy93** [comment]
Oh thanks so much, I hadn't even noticed that I miss-typed this.
I think the correct tags are `arm32v7` and `arm64v8`

**Review by Lissy93 — CHANGES_REQUESTED** [review]
Oh thanks so much, I hadn't even noticed that I miss-typed this.
I think the correct tags are arm32v7 and arm64v8

**Comment by walkxcode** [comment]
> Oh thanks so much, I hadn't even noticed that I miss-typed this. I think the correct tags are arm32v7 and arm64v8

Fixed it, accidentally removed a `v`...

**Review by Lissy93 — APPROVED** [review]
Thank you :) 💖

**Pull request merged**
